name: Build Swift Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.0.app 

      - name: Instalar dependências com CocoaPods
        run: pod install --repo-update
        working-directory: ./nome_do_seu_projeto 

      - name: Build o projeto
        run: xcodebuild -workspace toDoListSwift.xcworkspace -scheme toDoListSwiftschema -sdk iphonesimulator -configuration Debug build
  
      - name: Rodar testes
        run: xcodebuild test -workspace toDoListSwift.xcworkspace.xcworkspace -scheme toDoListSwiftschema -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
